name: Gold Monitor

on:
  schedule:
    - cron: "0,15,30,45 8-22 * * 1-5"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libraries
        run: |
          pip install yfinance requests

      - name: Run script
        run: python gold_monitor.py
